SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Models/ErrorViewModel.cs
namespace SinglePage_MasterDetails.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Models/MasterDBContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SinglePage_MasterDetails.Models
{
    public partial class MasterDBContext : DbContext
    {
        public MasterDBContext()
        {
        }

        public MasterDBContext(DbContextOptions<MasterDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<SaleDetail> SaleDetails { get; set; } = null!;
        public virtual DbSet<SaleMaster> SaleMasters { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB; Database=MasterDB; Trusted_Connection=true; Encrypt=false;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SaleDetail>(entity =>
            {
                entity.ToTable("SaleDetail");

                entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.ProductName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Qty).HasColumnType("decimal(18, 0)");
            });

            modelBuilder.Entity<SaleMaster>(entity =>
            {
                entity.HasKey(e => e.SaleId)
                    .HasName("PK__SaleMast__1EE3C3FFAD2CEC3D");

                entity.ToTable("SaleMaster");

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerAddress)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CustomerName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Gender)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Models/SaleDetail.cs
using System;
using System.Collections.Generic;

namespace SinglePage_MasterDetails.Models
{
    public partial class SaleDetail
    {
        public long SaleDetailId { get; set; }
        public long? SaleId { get; set; }
        public string? ProductName { get; set; }
        public decimal? Price { get; set; }
        public decimal? Qty { get; set; }
    }
}

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Models/SaleMaster.cs
using System;
using System.Collections.Generic;

namespace SinglePage_MasterDetails.Models
{
    public partial class SaleMaster
    {
        public long SaleId { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerAddress { get; set; }
        public string? Gender { get; set; }
    }
}

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SinglePage_MasterDetails.Models;
using System.Diagnostics;

namespace SinglePage_MasterDetails.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using SinglePage_MasterDetails.Models;
using SinglePage_MasterDetails.ViewModel;

namespace SinglePage_MasterDetails.Controllers
{
    public class SaleController : Controller
    {
        /*
         //this code is use for Migration, its can't work Scaffold

        private readonly MasterDBContext _dbContext;
        public SaleController(MasterDBContext dbContext)
        {
           _dbContext = dbContext;
        }  */

        MasterDBContext db = new MasterDBContext();
        public IActionResult Single(int? id)
        {
            VmSale oSale = new VmSale();
            var oSM = db.SaleMasters.Where(x => x.SaleId == id).FirstOrDefault();
            if (oSM != null)
            {
                oSale.SaleId = oSM.SaleId;
                oSale.CustomerName = oSM.CustomerName;
                oSale.CustomerAddress = oSM.CustomerAddress;
                oSale.Gender = oSM.Gender;
                oSale.CreateDate = oSM.CreateDate;
                var listDetail = new List<VmSale.VmSaleDetail>();
                var oSD = db.SaleDetails.Where(x => x.SaleId == id).ToList();
                foreach (var item in oSD)
                {
                    var oSaleDetial = new VmSale.VmSaleDetail();
                    oSaleDetial.SaleId = item.SaleId;
                    oSaleDetial.ProductName = item.ProductName;
                    oSaleDetial.Price = item.Price;
                    oSaleDetial.Qty = item.Qty;
                    listDetail.Add(oSaleDetial);
                }
                oSale.SaleDetails = listDetail;
            }
            oSale = oSale == null ? new VmSale() : oSale;
            ViewData["list"] = db.SaleMasters.ToList();
            return View(oSale);
        }
        [HttpPost]
        public IActionResult Single(VmSale model)
        {
            var oSalemaster = db.SaleMasters.Find(model.SaleId);
            if (oSalemaster == null)
            {
                oSalemaster = new SaleMaster();
                oSalemaster.SaleId = model.SaleId;
                oSalemaster.CreateDate = model.CreateDate;
                oSalemaster.CustomerName = model.CustomerName;
                oSalemaster.CustomerAddress = model.CustomerAddress;
                oSalemaster.Gender = model.Gender;
                db.SaleMasters.Add(oSalemaster);
            }
            else
            {
                oSalemaster.SaleId = model.SaleId;
                oSalemaster.CustomerName = model.CustomerName;
                oSalemaster.CustomerAddress = model.CustomerAddress;
                oSalemaster.Gender = model.Gender;
                oSalemaster.CreateDate = model.CreateDate;
                var listRem = db.SaleDetails.Where(x => x.SaleId == oSalemaster.SaleId).ToList();
                db.SaleDetails.RemoveRange(listRem);
            }
            db.SaveChanges();
            var listDetail = new List<SaleDetail>();
            for (var i = 0; i < model.ProductName.Length; i++)
            {
                if (!string.IsNullOrEmpty(model.ProductName[i]))
                {
                    var oSaleDetial = new SaleDetail();
                    oSaleDetial.SaleId = oSalemaster.SaleId;
                    oSaleDetial.ProductName = model.ProductName[i];
                    oSaleDetial.Price = model.Price[i];
                    oSaleDetial.Qty = model.Qty[i];
                    listDetail.Add(oSaleDetial);
                }
            }
            db.SaleDetails.AddRange(listDetail);
            db.SaveChanges();

            return RedirectToAction("Single");
        }
        public IActionResult Delete(int id)
        {
            var oSaleMaster = (from o in db.SaleMasters where o.SaleId == id select o).FirstOrDefault();
            var oDetail = (from o in db.SaleDetails where o.SaleId == id select o).ToList();
            if (oSaleMaster != null)
            {
                db.SaleMasters.Remove(oSaleMaster);
                db.SaleDetails.RemoveRange(oDetail);
                db.SaveChanges();
            }
            return RedirectToAction("Single");
        }

    }
}

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Views/Sale/Single.cshtml
@model SinglePage_MasterDetails.ViewModel.VmSale
@{

    ViewData["Title"] = "Single";
    var listsm = ViewData["list"] as List<SinglePage_MasterDetails.Models.SaleMaster>;
    var btn = Model.SaleId > 0 ? "Update" : "Add";
    var bc = Model.SaleId > 0 ? "btn btn-primary" : "btn btn-success";
    var i = 0;
}
<h2 style="text-align:center;">Single Page Master Details</h2>

<form asp-action="Single" asp-controller="Sale" method="post">

    <input type="hidden" asp-for="SaleId" />

    <div>
        CreateDate <br />
        <input type="date" asp-for="CreateDate" />
    </div>

    <div>
        CustomerName <br />
        <input type="text" asp-for="CustomerName" />
    </div>

    <div>
        CustomerAddress <br />
        <input type="text" asp-for="CustomerAddress" />
    </div>

    <div>
        <label asp-for="Gender"></label>
        <br />
        <input type="radio" asp-for="Gender" name="Gender" value="Male" checked="@Model.Gender == " Male"" />
        <label asp-for="Gender" class="form-check-label">Male</label>
        <br />
        <input type="radio" asp-for="Gender" name="Gender" value="Female" checked="@Model.Gender == " Female"" />
        <label asp-for="Gender" class="form-check-label">Female</label>
    </div>

    @await Html.PartialAsync("_ValidationScriptsPartial", Model)

    <table>
        <thead>
            <tr>
                <td>ProductName</td>
                <td>Price</td>
                <td>Qty</td>
                <td><button type="button" onclick="AddItem()">Add More</button></td>
            </tr>
        </thead>
        <tbody id="tSD">
            @foreach (var item in Model.SaleDetails)
            {
                i++;
                <tr id="tr_@i">
                    <td><input type="text" id="ProductName_@i" name="ProductName" value="@item.ProductName" /></td>
                    <td><input type="number" id="Price_@i" name="Price" value="@item.Price" /></td>
                    <td><input type="number" id="Qty_@i" name="Qty" value="@item.Qty" /></td>
                </tr>
            }
        </tbody>
    </table>
    <div>
    </div>
    <div>
        <button type="submit" class="@bc">@btn</button>
        <a asp-action="Single" class="btn btn-info">Reset</a>
    </div>

</form>

@{

}

@await Html.PartialAsync("_PartialView", Model)


<script>

    //Ajax JQuery for GET method

    $(document).ready(function () {
        $("#load-page").click(function () {
            $.ajax({
                url: "/Home/Single",
                type: "GET",
                dataType: "html",
                success: function (result) {
                    $("#page-content").html(result);
                },
                error: function () {
                    alert("An error occurred while loading the page.");
                }
            });
        });
    });

    //Ajax JQuery for POST method

    $(document).ready(function () {
        $("#my-form").submit(function (event) {
            event.preventDefault();
            var formData = $(this).serialize();
            $.ajax({
                url: "/Home/Single",
                type: "POST",
                data: formData,
                dataType: "json",
                success: function (result) {
                    $("#result").html("CustomerName: " + result.name + "<br>Gender: " + result.gender);
                },
                error: function () {
                    alert("An error occurred while submitting the data.");
                }
            });
        });
    });

    var i = @i;
    function AddItem() {
        i += 1;
        var Trs = '<tr id="tr_' + i + '"><td><input type="text" id = "ProductName_' + i + '" name = "ProductName" value = "0"/></td>' + '<td><input type="number" id = "Price_' + i + '" name = "Price" value = "0"/></td>' + '<td><input type="number" id="Qty_@i" name="Qty"/></td>' + '</tr>';
        document.getElementById('tSD').innerHTML += Trs;
    }


</script>

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SinglePage_MasterDetails</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SinglePage_MasterDetails.styles.css" asp-append-version="true" />
    <style>
        body{
            background-color: paleturquoise;
        }
        .navbar{
            background-color: steelblue;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SinglePage_MasterDetails</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SinglePage_MasterDetails - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SinglePage_MasterDetails_CoreMVC-master/SinglePage_MasterDetails/Views/Shared/_PartialView.cshtml
@model SinglePage_MasterDetails.ViewModel.VmSale
@{
    var index = 0;
    var listsm = ViewData["list"] as List<SinglePage_MasterDetails.Models.SaleMaster>;

}

<table class="table table-striped">
    <tr>

        <th>Date & Time</th>
        <th>Customer Name</th>
        <th>Address</th>
        <th>Gender</th>
        <th>#####</th>
        <th>#####</th>
    </tr>
    @foreach (var item in listsm)
    {
        <tr>
            <td>@item.CreateDate</td>
            <td>@item.CustomerName</td>
            <td>@item.CustomerAddress</td>
            <td>@item.Gender</td>
            <td><a asp-action="Single" asp-route-id="@item.SaleId">Edit</a></td>
            <td><a asp-action="Delete" asp-route-id="@item.SaleId">Delete</a></td>
        </tr>

    }
</table>